jwt:
  header: Authorization
  secretKey: dGVzdGtleS1ob21lYnJld2NsdWItd2Vic2l0ZS1zZWNyZXRLZXk=
  refreshKey: dGVzdGtleS1ob21lYnJld2NsdWItd2Vic2l0ZS1zZWNyZXRLZXk=
  # secretKey : 'testkey-homebrewclub-website-secretKey' ? base64? ???? ?
  ## ??? gitignore? ???, secretKey? ?? ?.

spring:
  data:
    redis:
      host : localhost
      port : 6379

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testlogin?useUnicode=true&serverTimezone=Asia/Seoul
    username: user1
    password: 1234
    driver-class: com.mysql.cj.jdbc.Driver

